apiVersion: v1
kind: Service
metadata:
  namespace: airflow
  name: flower  
spec:
  type: LoadBalancer
  selector:
    app: airflow
    tier: flower
  ports:
    - name: flower
      protocol: TCP
      port: 5555
