apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: airflow
spec:
  type: ClusterIP
  selector:
    app: airflow
    tier: redis
  ports:
    - name: node
      protocol: TCP
      port: 6379
      targetPort: node