apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: airflow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: redis
    spec:
      restartPolicy: Always
      containers:
      - name: redis
        image: redis:3.2.7
        ports:
        - name: node
          containerPort: 6379  